// Android packaging: Capacitor-ready. Native camera/filesystem/share plugins can be wired here for production OCR and invoice sharing.\nconst KEY="moms-pride-v1";
let db=JSON.parse(localStorage.getItem(KEY)||'{"products":[],"customers":[],"suppliers":[],"transactions":[],"accounts":[{"name":"Cash","balance":0},{"name":"UPI","balance":0},{"name":"Bank","balance":0},{"name":"Card","balance":0}],"review":[]}');
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2});
const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const app=document.getElementById("app");
function shell(title,body){app.innerHTML=`<header class="top"><div class="brand">Mom's Pride</div><div class="sub">Billing • Inventory • Transactions</div></header><main class="wrap"><h2>${title}</h2><div class="nav">${["Dashboard","New Sale","Purchases","Products","Customers","Suppliers","Payments","Expenses","Review Queue"].map(x=>`<button onclick="route('${x}')">${x}</button>`).join("")}</div>${body}</main>`}
function route(x){({Dashboard:dashboard,"New Sale":sale,Purchases:purchases,Products:products,Customers:customers,Suppliers:suppliers,Payments:payments,Expenses:expenses,"Review Queue":review}[x]||dashboard)()}
function dashboard(){let t=db.transactions, sales=t.filter(x=>x.type==="sale").reduce((a,x)=>a+x.total,0), pur=t.filter(x=>x.type==="purchase").reduce((a,x)=>a+x.total,0), exp=t.filter(x=>x.type==="expense").reduce((a,x)=>a+x.total,0), low=db.products.filter(p=>(p.stock||0)<=(p.min||0));shell("Dashboard",`<div class="grid"><div class="card"><div class="label">Total Sales</div><div class="metric">${money(sales)}</div></div><div class="card"><div class="label">Purchases</div><div class="metric">${money(pur)}</div></div><div class="card"><div class="label">Expenses</div><div class="metric">${money(exp)}</div></div><div class="card"><div class="label">Review Queue</div><div class="metric">${db.review.length}</div></div></div><div class="card" style="margin-top:12px"><div class="row"><b>Quick Actions</b><div class="actions"><button class="btn primary" onclick="route('New Sale')">New Sale</button><button class="btn" onclick="route('Purchases')">New Purchase</button><button class="btn" onclick="route('Payments')">Receive/Pay</button><button class="btn" onclick="route('Expenses')">Expense</button></div></div></div><div class="card" style="margin-top:12px"><b>Low Stock</b>${low.length?`<div class="list">${low.map(p=>`<div class="item row"><span>${p.name}</span><span>${p.stock||0} ${p.unit||"pcs"}</span></div>`).join("")}</div>`:`<div class="empty">No low-stock products</div>`}</div>`)}
function products(){shell("Products & Inventory",`<div class="card"><form class="form" onsubmit="addProduct(event)"><div class="two"><input id="pn" placeholder="Product name" required><input id="sku" placeholder="SKU / Barcode"></div><div class="two"><input id="buy" type="number" placeholder="Purchase price"><input id="sell" type="number" placeholder="Selling price" required></div><div class="two"><input id="stock" type="number" placeholder="Opening stock" value="0"><input id="min" type="number" placeholder="Minimum stock" value="0"></div><button class="btn primary">Add Product</button></form></div><div class="list">${db.products.map(p=>`<div class="item row"><div><b>${p.name}</b><div class="sub">${p.sku||"No barcode"} • Buy ${money(p.buy)} • Sell ${money(p.sell)}</div></div><b>${p.stock||0}</b></div>`).join("")||'<div class="empty">No products yet</div>'}</div>`)}
function addProduct(e){e.preventDefault();db.products.push({id:id(),name:pn.value,sku:sku.value,buy:+buy.value||0,sell:+sell.value||0,stock:+stock.value||0,min:+min.value||0});save();products()}
function sale(){shell("New Sale",`<div class="card"><div class="form"><input id="search" placeholder="Search product / barcode" oninput="renderSale()"><div id="saleitems"></div><div class="two"><select id="pay"><option>Cash</option><option>UPI</option><option>Card</option><option>Bank</option><option>Credit</option></select><input id="customer" placeholder="Customer (optional)"></div><div class="row"><b>Total</b><b id="total">₹0</b></div><button class="btn primary" onclick="finalizeSale()">Finalize Sale → Review Queue</button></div></div>`);renderSale()}
function renderSale(){let q=(search?.value||"").toLowerCase(), ps=db.products.filter(p=>p.name.toLowerCase().includes(q)||(p.sku||"").toLowerCase().includes(q));saleSelected=ps.slice(0,5);document.getElementById("saleitems").innerHTML=saleSelected.map((p,i)=>`<div class="item row"><span><b>${p.name}</b><br><small>${money(p.sell)} • Stock ${p.stock}</small></span><input style="width:70px;padding:8px" type="number" min="1" value="${cart[p.id]||0}" onchange="cart['${p.id}']=+this.value;renderSale()"></div>`).join("")||'<div class="empty">No matching products</div>';let total=Object.entries(cart).reduce((s,[pid,q])=>s+(db.products.find(p=>p.id===pid)?.sell||0)*q,0);document.getElementById("total").textContent=money(total)}
let cart={},saleSelected=[];
function finalizeSale(){let lines=Object.entries(cart).filter(([_,q])=>q>0).map(([pid,q])=>{let p=db.products.find(x=>x.id===pid);return {productId:pid,name:p.name,qty:q,rate:p.sell,amount:q*p.sell}});if(!lines.length)return alert("Add at least one product.");let total=lines.reduce((s,x)=>s+x.amount,0);db.review.unshift({id:id(),type:"sale",date:new Date().toISOString(),total,lines,payment:pay.value,customer:customer.value,status:"Pending Review"});save();cart={};alert("Sale added to Review Queue.");route("Review Queue")}
function purchases(){shell("Purchases",`<div class="card"><h3>Upload / Scan Supplier Bill</h3><p class="sub">Select an image or PDF. The production version will extract supplier, invoice, items and GST for review before posting.</p><input type="file" accept="image/*,.pdf" onchange="billUpload(event)"></div><div class="card" style="margin-top:12px"><h3>Manual Purchase</h3><form class="form" onsubmit="manualPurchase(event)"><div class="two"><input id="sup" placeholder="Supplier"><input id="pinv" placeholder="Invoice number"></div><input id="pamount" type="number" placeholder="Total amount" required><button class="btn primary">Add Purchase → Review Queue</button></form></div>`)}
function billUpload(e){let f=e.target.files[0];if(!f)return;db.review.unshift({id:id(),type:"purchase",date:new Date().toISOString(),total:0,supplier:"Extract from uploaded bill",invoice:"",attachment:f.name,status:"Needs OCR"});save();alert("Bill uploaded. It is now waiting for OCR/review.");route("Review Queue")}
function manualPurchase(e){e.preventDefault();db.review.unshift({id:id(),type:"purchase",date:new Date().toISOString(),total:+pamount.value,supplier:sup.value,invoice:pinv.value,status:"Pending Review"});save();alert("Purchase added to Review Queue.");route("Review Queue")}
function review(){shell("Review Queue",`<div class="list">${db.review.map(x=>`<div class="item"><div class="row"><b>${x.type.toUpperCase()}</b><span class="status">${x.status}</span></div><p>${x.supplier||x.customer||""} ${x.invoice?"• Invoice "+x.invoice:""}</p><div class="row"><b>${money(x.total)}</b><div class="actions"><button class="btn primary" onclick="approve('${x.id}')">Approve & Send to Tally</button><button class="btn" onclick="removeReview('${x.id}')">Void</button></div></div></div>`).join("")||'<div class="empty">Nothing waiting for review.</div>'}<div class="sub" style="margin-top:14px">Tally integration placeholder: approved transactions will be sent through the Tally Bridge once configured.</div></div>`)}
function approve(i){let x=db.review.find(r=>r.id===i);if(!x)return;x.status="Sent to Tally (Demo)";db.transactions.push({...x});db.review=db.review.filter(r=>r.id!==i);save();alert("Approved. Demo Tally status recorded.");review()}
function removeReview(i){db.review=db.review.filter(r=>r.id!==i);save();review()}
function simpleList(title,kind){let arr=db[kind];shell(title,`<div class="card"><form class="form" onsubmit="addParty(event,'${kind}')"><input id="name" placeholder="${title.slice(0,-1)} name" required><input id="phone" placeholder="Phone"><button class="btn primary">Add</button></form></div><div class="list">${arr.map(x=>`<div class="item row"><span><b>${x.name}</b><br><small>${x.phone||""}</small></span></div>`).join("")||'<div class="empty">No records yet</div>'}</div>`)}
function addParty(e,k){e.preventDefault();db[k].push({id:id(),name:name.value,phone:phone.value});save();simpleList(k==="customers"?"Customers":"Suppliers",k)}
function customers(){simpleList("Customers","customers")} function suppliers(){simpleList("Suppliers","suppliers")}
function payments(){shell("Payments / Receipts",`<div class="card"><form class="form" onsubmit="addTxn(event,'payment')"><select id="direction"><option value="in">Money Received</option><option value="out">Money Paid</option></select><input id="party" placeholder="Party"><input id="amt" type="number" placeholder="Amount" required><select id="account"><option>Cash</option><option>UPI</option><option>Bank</option><option>Card</option></select><input id="note" placeholder="Reference / notes"><button class="btn primary">Save → Review Queue</button></form></div>`)}
function expenses(){shell("Expenses",`<div class="card"><form class="form" onsubmit="addTxn(event,'expense')"><select id="cat"><option>Rent</option><option>Electricity</option><option>Salary</option><option>Transport</option><option>Packaging</option><option>Repairs</option><option>Marketing</option><option>Delivery</option><option>Miscellaneous</option></select><input id="amt" type="number" placeholder="Amount" required><select id="account"><option>Cash</option><option>UPI</option><option>Bank</option><option>Card</option></select><input id="note" placeholder="Notes"><button class="btn primary">Save → Review Queue</button></form></div>`)}
function addTxn(e,type){e.preventDefault();let a=+amt.value;db.review.unshift({id:id(),type,total:a,date:new Date().toISOString(),party:party?.value||cat.value,account:account.value,note:note.value,status:"Pending Review"});save();alert("Transaction added to Review Queue.");review()}
dashboard();
